In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
visa=pd.read_csv(r"C:\Users\Suman\Documents\Naresh IT\data files\Visadataset.csv")

In [3]:
bank=pd.read_csv(r"C:\Users\Suman\Documents\Naresh IT\data files\bank.csv",sep=';')

In [5]:
visa.head(3)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied

In [6]:
keys=visa.dtypes.keys().tolist()
values=visa.dtypes.values.tolist()

In [13]:
cat=[]
num=[]
for i,j in zip(values,keys):
    if i=='object':
        cat.append(j)
    else:
        num.append(j)

print('category:',cat)
print('numeric:',num)

category: ['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position', 'case_status']
numeric: ['no_of_employees', 'yr_of_estab', 'prevailing_wage']

- Frequency Table
- Relative Frequency Table
- Bar Chart
- Pie Chart

### **step-3: Frequency Table**

In [16]:
visa['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [17]:
visa['continent'].nunique()

6

- there are 25480 applicants form 6 continents
- number of applicants form each continent: **Frequency Table**
- x-axis: continents (class)
- y-axis: frequency

In [ ]:
asia: how many
africa: how many ------== called Frequency

In [6]:
# Number f applicants from "Asia"
visa   # df
visa['continent']   # selecting one column
cont=visa['continent']=='Asia'
cont# checking one class
#cont
# if true returns 1
# if false returns 0

0         True
1         True
2         True
3         True
4        False
         ...
25475     True
25476     True
25477     True
25478     True
25479     True
Name: continent, Length: 25480, dtype: bool

In [21]:
np.sum(cont)   # counting no of Asia paricipants in the data frame

np.int64(16861)

In [22]:
visa[cont]    # displaying the data where continent is == 'Asia'

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.1400,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [17]:
cont=visa['continent'].unique()
freq=[]
for i in cont:
    count=visa['continent']==i    #asia
    freq.append(np.sum(count))

df=pd.DataFrame(zip(cont,freq),columns=['Continent_class','frequency'])
df

  Continent_class  frequency
0            Asia      16861
1          Africa        551
2   North America       3292
3          Europe       3732
4   South America        852
5         Oceania        192

### value_Counts`

In [33]:
visa['continent'].value_counts()

continent
Asia             16861
Europe            3732
North America     3292
South America      852
Africa             551
Oceania            192
Name: count, dtype: int64

In [30]:
keys=visa['continent'].value_counts().keys().tolist()
values=visa['continent'].value_counts().values.tolist()

array([16861,  3732,  3292,   852,   551,   192])

In [29]:
df=pd.DataFrame(zip(keys,values),columns=['Class','Frequency'])
df

           Class  Frequency
0           Asia      16861
1         Europe       3732
2  North America       3292
3  South America        852
4         Africa        551
5        Oceania        192

In [50]:
visa.groupby(by='continent').count()['case_id']

continent
Africa             551
Asia             16861
Europe            3732
North America     3292
Oceania            192
South America      852
Name: case_id, dtype: int64