In [1]:
import numpy as np
import pandas as pd

In [2]:
d={'Names':['Rohitha','Sumanth','Deepika',None],
   'Age':[None,22,24,25],
   'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

     Names   Age  City
0  Rohitha   NaN   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3     None  25.0  None

In [3]:
df1.to_csv('data1.csv',index=False)

In [4]:
d={'Names':['Rohitha','Sumanth','Deepika',np.nan],
   'Age':[np.nan,22,24,25],
   'City':['Hyd','Blr','Pune',np.nan]}
df2=pd.DataFrame(d)
df2

     Names   Age  City
0  Rohitha   NaN   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3      NaN  25.0   NaN

- categorical data use None
- Numerical data use np.nan

In [6]:
np.nan+10

20

In [8]:
df1.isnull()
# isnull= is a method where it displays True when a Null value occurs

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False  False
3   True  False   True

In [10]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [11]:
df1.values

array([['Rohitha', nan, 'Hyd'],
       ['Sumanth', 22.0, 'Blr'],
       ['Deepika', 24.0, 'Pune'],
       [None, 25.0, None]], dtype=object)

In [12]:
df2.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False  False
3   True  False   True

In [13]:
df2.values

array([['Rohitha', nan, 'Hyd'],
       ['Sumanth', 22.0, 'Blr'],
       ['Deepika', 24.0, 'Pune'],
       [nan, 25.0, nan]], dtype=object)

- df1.values
- df1.dtypes
- df1.isnull()
- df1.isnull().sum()

In [14]:
data=pd.read_csv(r"data1.csv")
data

     Names   Age  City
0  Rohitha   NaN   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3      NaN  25.0   NaN

**fill the values**

In [16]:
# Random filling
df1.fillna(30)

     Names   Age  City
0  Rohitha  30.0   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3       30  25.0    30

In [17]:
# select one column and fill with value
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: object

In [ ]:
#pad,ffill,bfill,backfill
#axis=0 axis=1
df1.fillna(df1.fillna(
    value: 'Hashable | Mapping | Series | DataFrame | None' = None,
    *,
    method: 'FillnaOptions | None' = None,
    axis: 'Axis | None' = None,
    inplace: 'bool_t' = False,)

In [18]:
df1.fillna(method='pad')

C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\3887010614.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

     Names   Age  City
0  Rohitha   NaN   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3  Deepika  25.0  Pune

In [20]:
df1.fillna(method='pad',axis=1)

C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)
C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\1258234312.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.fillna(method='pad',axis=1)

     Names      Age  City
0  Rohitha  Rohitha   Hyd
1  Sumanth     22.0   Blr
2  Deepika     24.0  Pune
3      NaN     25.0  25.0

In [21]:
df1.fillna(method='bfill')

C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

     Names   Age  City
0  Rohitha  22.0   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3     None  25.0  None

In [22]:
df1.fillna(method='bfill',axis=1)

C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\2900121331.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)
C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\2900121331.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.fillna(method='bfill',axis=1)

     Names   Age  City
0  Rohitha   Hyd   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3     25.0  25.0   NaN

In [23]:
df1.fillna(method='ffill')

C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\598575452.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')

     Names   Age  City
0  Rohitha   NaN   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3  Deepika  25.0  Pune

In [24]:
df1.fillna(method='backfill')

C:\Users\Suman\AppData\Local\Temp\ipykernel_18212\2955370104.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='backfill')

     Names   Age  City
0  Rohitha  22.0   Hyd
1  Sumanth  22.0   Blr
2  Deepika  24.0  Pune
3     None  25.0  None

- mean fill
- median fill
- mode
fill

In [26]:
age_mean=round(df1['Age'].mean())
df1['Age'].fillna(age_mean)

0    24.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [27]:
age_median=round(df1['Age'].median())
df1['Age'].fillna(age_median)

0    24.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [29]:
age_mode=df1['Age'].mode()
df1['Age'].fillna(age_mode)

0    22.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [30]:
# there is no particular rule how to fill the missing values
# it is completely based on situation

**Situation-1**

In [35]:
gender=['male','female',None]
d1=pd.DataFrame(gender,columns=['gender'])

In [36]:
d1 # I want to handover this data to my student with not encode

   gender
0    male
1  female
2    None

In [37]:
d={'female':0,'male':1}
d1['gender']=d1['gender'].map(d)
d1

   gender
0       1
1       0
2      10

In [38]:
# the student think that I want to fill a missing
# data is numerical: mean
(1+0)/2

0.5

In [ ]:
0.5 indicates a wrong value it doesnt indicate a gender

**Situation-2**

In [ ]:
# ML Algorithm
# Churn : Stay or Not stay
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**Situation-3**

In [39]:
# no of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

doesnt indicate a correct no of days

**Situation-4**

In [42]:
course=['DS','AI','DS','DEVOPS','AI','DEVOPS','AI']
FEE=[30000,25000,30000,22000,27000,22000,None]
df=pd.DataFrame(zip(course,FEE))
df

        0        1
0      DS  30000.0
1      AI  25000.0
2      DS  30000.0
3  DEVOPS  22000.0
4      AI  27000.0
5  DEVOPS  22000.0
6      AI      NaN

## KNNImputer

- KNN: K-nearest neighbours
- where k is a number
- instead of taking avg of all the values data
    - first we will find the neighbours who are close with missing data
    - by using Euclidian distance calculation will identify the neighbour rows
    - suppose k=2 will identify the two closest rows
    - those closest rows values will take itm will calculate the mean
    - finally will fill with the mean

In [2]:
Salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(Salary,age),
                columns=['salary','age'])
df

    salary  age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn
  - impute
    - KNNImputer

In [4]:
from sklearn.impute import KNNImputer

In [10]:
imputer=KNNImputer(n_neighbors=2)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0