In [ ]:
**data life cycle**
                        Data Read
                            |
                        Data Cleaning
                            |
                        Data Analysis
                            |
                        Feature Engineering
                            |
                        Feature Selection
                            |
                        Model Development
                            |
                        Model Evaluation
                            |
                        Model Tuning
                            |
                        Model Deployment

## **Feature Engineering**

- so far we have performed feature analysis
    - Data Frame quick check
    - Categorical column analysis
    - Bar Charts, Pie charts
    - Numerical column analysis
    - Histograms, box plots, outliers
    - Bivariate, Multivariate analysis
    - correlation
- now in **Feature Engineering** we will be learing the following:
    - we will create a new columns for better ML models
    - we will perform the **Encoding**, which is convert categorical to Numerical data
    - we will do the data **Transformations**
    - we will perform **Scaling : Standardization and Normalization**
    - we will perform the **missing values analysis**
- Simply feature engineering means our data will be modified

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

visa_data=pd.read_csv(r"C:\Users\Suman\Documents\Naresh IT\data files\Visadataset.csv")
num=visa_data.select_dtypes(exclude='object').columns
cat=visa_data.select_dtypes(include='object').columns

In [2]:
num,cat

(Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'),
 Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'))

In [3]:
visa_data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

# encoding

1. case_status column
2. take unique values from column
3. create a dictionary and give the numerical values to the unique value
4. map the dictionary with original colulmn
5. categorical column converted to numericla column

In [6]:
visa_data['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [9]:
d={'Certified':0,'Denied':1}

In [10]:
visa_data['case_status']=visa_data['case_status'].map(d)

In [11]:
visa_data['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

1. education_of_employee

In [13]:
visa_data['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [16]:
d2={"Bachelor's":0,'Doctorate':1,'High School':2,"Master's":3}
visa_data['education_of_employee']=visa_data['education_of_employee'].map(d2)

In [17]:
visa_data['education_of_employee']

0        2
1        3
2        0
3        0
4        3
        ..
25475    0
25476    2
25477    3
25478    3
25479    0
Name: education_of_employee, Length: 25480, dtype: int64

In [ ]:
infant   kid   teenage   adult   midage   oldage   
0         1      2          3      4       5         ordinal encoder 

adult   infant   kid   midage  oldage teenage  
0         1       2     3        4      5           nomial/label encoder ( alphabetical order) wrong X

red pink yellow orange 
pink orange red yellow 
0      1     2    3       label encoder/ nomial encoder

In [ ]:
education      Label Encoder       Ordinal Encoder
====================================================
High SChool          1                 0

bachelor             0                 1

masters              2                 2

Ph.D                 3                 3


1 0 2 3 ==> Ml model sees this as : 3>2>1>0
which indicates: PHD>Masters>HighCShool> Bachelor
which is a bad 
because the data must be in an order of education oriented no alphabetical order
so this type of data is called ordinal data which had to follow the order 


red black blue : nominal data no order
good great greatest : ordinal data which has to follow the order

In [23]:
visa_data=pd.read_csv(r"C:\Users\Suman\Documents\Naresh IT\data files\Visadataset.csv")

In [22]:
visa_data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [ ]:
- sklearn : **Package**
    - preprocessing : **module**
        - labelencoder : **class**
            -  fit_transform : **method**
1.
import sklearn
sklearn.preprocessing

2.
from sklearn import preprocessing
dir(preprocessing) : LabelEncoder
preprocessing.LabelEncoder

3.
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
fe.fit_transform

4.
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform

fit transform
- fit: created a dictionary (find something)
- transform: using above finding we are modify the data

In [ ]:
from sklearn.module import class
va=class()
va.fit   or va.fit_transform

## Label Encoder

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_data['case_status']=le.fit_transform(visa_data['case_status'])
visa_data['continent']=le.fit_transform(visa_data['continent'])

In [11]:
visa_data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:    # dont consider case id
    visa_data[i]=le.fit_transform(visa_data[i])

In [13]:
visa_data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [18]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
for i in cat[1:]:
    visa_data[i]=oe.fit_transform(visa_data[[i]])
visa_data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

In [19]:
visa_data[['continent']]

       continent
0            1.0
1            1.0
2            1.0
3            1.0
4            0.0
...          ...
25475        1.0
25476        1.0
25477        1.0
25478        1.0
25479        1.0

[25480 rows x 1 columns]

## pd.get_dummies  ( also called One-Hot Encoder)

In [26]:
visa_data['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

- get dummies is a way to represent the categorical columns into numerical
- first it will check what are the labels in a column
- for ex: case_status has 2 labels
      - denied and certified
- so it will create two new columns based on labels
    - col1: case_status_Denied
    - col2: case_status_certified
- new columns are **independent** to eachother (90Degree)
- also called as **One-Hot encoder**
- some of ML algorithms expect that columns should be **independent** each other

case_status | case_status_certified | case_status_denied
 denied     |          0            |         1
 certified  |          1            |         0
 certified  |          1            |         0

In [28]:
pd.get_dummies(visa_data['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [30]:
visa_data['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [29]:
pd.get_dummies(visa_data['education_of_employee'],dtype=int)

       Bachelor's  Doctorate  High School  Master's
0               0          0            1         0
1               0          0            0         1
2               1          0            0         0
3               1          0            0         0
4               0          0            0         1
...           ...        ...          ...       ...
25475           1          0            0         0
25476           0          0            1         0
25477           0          0            0         1
25478           0          0            0         1
25479           1          0            0         0

[25480 rows x 4 columns]

In [5]:
sorted(visa_data['region_of_employment'].unique())

['Island', 'Midwest', 'Northeast', 'South', 'West']

In [7]:
d3={'Island':100, 'Midwest':250, 'Northeast':300, 'South':50, 'West':1}

In [8]:
visa_data['region_of_employment']=visa_data['region_of_employment'].map(d3)

In [9]:
visa_data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,1,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,300,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,1,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,1,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,50,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,50,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,300,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,50,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,1,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,250,70876.9100,Year,Y,Certified

In [26]:
cols=sorted(visa_data['continent'].unique())
val={}
for i,j in enumerate(cols):
    val[j]=i
visa_data['continent']=visa_data['continent'].map(val)

In [ ]:
enumerate africa:0
          Asia :1
          Europe:2

In [27]:
visa_data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [42]:
y=visa_data['education_of_employee']

In [9]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform(visa_data[['education_of_employee']])

array([[2.],
       [3.],
       [0.],
       ...,
       [3.],
       [3.],
       [0.]], shape=(25480, 1))

In [ ]:
h b m d 
0 1 2 3

In [34]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(y)

array([2, 3, 0, ..., 3, 3, 0], shape=(25480,))

In [3]:
education=sorted(visa_data['education_of_employee'].unique())

In [37]:
visa_data['education_of_employee']

0        High School
1           Master's
2         Bachelor's
3         Bachelor's
4           Master's
            ...
25475     Bachelor's
25476    High School
25477       Master's
25478       Master's
25479     Bachelor's
Name: education_of_employee, Length: 25480, dtype: object

In [ ]:
["Bachelor's", 'Doctorate', 'High School', "Master's"]
0                 1            2             3